### ISSUE TITLE
TS error when using option `attribute` for Animation.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/twixt#31]
I encountered this when converting function-builder `NotInvertibleSymbolNode` to TypeScript.  It uses the `attribute` option of Animation, like this:

```ts
    this.animation = new Animation( {
      duration: 1.5, // seconds
      easing: Easing.QUADRATIC_IN_OUT,
      object: this,
      attribute: 'opacity',
      from: 0.85,
      to: 0
    } );
```

... resulting in TS error: "TS2322: Type string is not assignable to type".

Maybe I need to parameterize `Animation<...>`?  But I don't see any examples in the doc or in PhET code, and this declaration is impossible to grok:

```ts
class Animation<SelfType = unknown, SelfObjectType = unknown, TargetTypes = unknown[], TargetObjectTypes extends { [K in keyof TargetTypes]: unknown } = { [K in keyof TargetTypes]: unknown }> extends Disposable {
```

I'll use`@ts-expect-error` in NotInvertibleSymbolNode.ts for now.  @jonathanolson can you please look at this, and recommend how to address?

**Comment by pixelzoom** [comment]
@jonathanolson ping.

**Comment by jonathanolson** [comment]
This falls back to the `this` type not being concrete, so when we have `KeysMatching<this, number>` (i.e. the string union type of keys that this[key]:number), TypeScript apparently bails.

I don't currently have a great fix for this in KeysMatching (or the use case in InternalAnimationTargetOptions). Tried a good number of workarounds with no success.

Recommended workaround is to cast the `this` reference so that it is a concrete type, i.e. replace `object: this` with `object: this as NotInvertibleSymbolNode,`. The type issue goes away once that is done.

**Comment by pixelzoom** [comment]
Thanks @jonathanolson.  That is indeed unfortunate. But it doesn't seem worth more work at this point, so I've added the cast as suggested.  Closing.
